#!/usr/bin/env bash
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CPSYCLE="$ROOT/cpsycle"
OUT="${1:-$ROOT/build-audit}"
mkdir -p "$OUT/logs"

REPORT="$OUT/summary.md"
: > "$REPORT"

status_rows=()

run_stage() {
    local id="$1"
    local label="$2"
    shift 2
    local log="$OUT/logs/${id}.log"

    printf '## %s\n\n' "$label" >> "$REPORT"
    printf 'Command: `%s`\n\n' "$*" >> "$REPORT"

    set +e
    (cd "$CPSYCLE" && "$@") >"$log" 2>&1
    local rc=$?
    set -e

    if [ "$rc" -eq 0 ]; then
        status_rows+=("| ${label} | PASS | ${rc} | logs/${id}.log |")
    else
        status_rows+=("| ${label} | FAIL | ${rc} | logs/${id}.log |")
    fi

    printf 'Exit code: `%s`\n\n' "$rc" >> "$REPORT"
    printf 'Last 80 log lines:\n\n```text\n' >> "$REPORT"
    tail -n 80 "$log" >> "$REPORT" || true
    printf '\n```\n\n' >> "$REPORT"
}

record_environment() {
    {
        echo '# PSYCLE-LINUX Phase 2 Build Audit'
        echo
        echo 'Generated by `scripts/phase2-build-audit.sh`.'
        echo
        echo '## Environment'
        echo
        echo '```text'
        uname -a
        echo
        if command -v lsb_release >/dev/null 2>&1; then lsb_release -a 2>/dev/null || true; fi
        echo
        gcc --version | head -n 1 || true
        g++ --version | head -n 1 || true
        make --version | head -n 1 || true
        pkg-config --version || true
        echo '```'
        echo
        echo '## pkg-config integration points'
        echo
        echo '| module | version | cflags | libs |'
        echo '| --- | --- | --- | --- |'
    } >> "$REPORT"

    for module in lua lua5.4 lilv-0 freetype2 fontconfig x11 xft xext xmu alsa jack sdl2 fluidsynth; do
        local version cflags libs
        version="$(pkg-config --modversion "$module" 2>/dev/null || true)"
        cflags="$(pkg-config --cflags "$module" 2>/dev/null || true)"
        libs="$(pkg-config --libs "$module" 2>/dev/null || true)"
        [ -n "$version" ] || version='MISSING'
        printf '| `%s` | `%s` | `%s` | `%s` |\n' "$module" "$version" "$cflags" "$libs" >> "$REPORT"
    done
    echo >> "$REPORT"
}

set -e
record_environment

# Start from a repeatable source-tree state. Historical makefiles have imperfect
# clean targets, so cleaning is evidence too but must not abort the audit.
run_stage clean-top-level 'Top-level clean' make clean

# Build libraries in dependency order so each layer has an independent result.
run_stage core-container 'Core: container' make -C container/src
run_stage core-thread 'Core: thread' make -C thread/src
run_stage core-script 'Core: script' make -C script/src
run_stage core-file 'Core: file' make -C file/src
run_stage core-dsp 'Core: DSP' make -C dsp/src
run_stage ui-x11 'UI: X11/Xft' make -C ui/src
run_stage core-luaui 'Core: Lua UI' make -C luaui/src
run_stage core-audio 'Core: audio engine' make -C audio/src

# Linux drivers are checked independently.
run_stage driver-alsa 'Driver: ALSA' make -C driver/alsa
run_stage driver-alsamidi 'Driver: ALSA MIDI' make -C driver/alsamidi
run_stage driver-jack 'Driver: JACK' make -C driver/jack
run_stage driver-sdl2 'Driver: SDL2' make -C driver/sdl2
run_stage driver-evjoystick 'Driver: event joystick' make -C driver/evjoystick

# Smaller executable first, then the host and native machines.
run_stage player 'psyplayer' make player
run_stage host 'Native X11 host' make host
run_stage plugins 'Native plugin set' make plugins
run_stage drivers-aggregate 'Aggregate Linux drivers' make drivers
run_stage full-build 'Top-level make all' make all

# Prepend the compact status table so the report is readable without opening logs.
TMP="$OUT/summary.tmp"
{
    sed -n '1,/## pkg-config integration points/p' "$REPORT"
    # Environment table already follows the heading; include through its blank line.
} > /dev/null

TABLE="$OUT/status-table.md"
{
    echo '## Stage status'
    echo
    echo '| stage | result | exit | log |'
    echo '| --- | --- | ---: | --- |'
    printf '%s\n' "${status_rows[@]}"
    echo
} > "$TABLE"

python3 - "$REPORT" "$TABLE" <<'PY'
from pathlib import Path
import sys
report = Path(sys.argv[1])
table = Path(sys.argv[2]).read_text()
text = report.read_text()
needle = '## Environment\n'
pos = text.find(needle)
if pos == -1:
    raise SystemExit('Environment heading missing')
# Put stage status after the pkg-config table, before stage details. A simple
# marker at the first stage heading is deterministic for this script.
first_stage = text.find('## Top-level clean')
if first_stage == -1:
    raise SystemExit('First stage heading missing')
text = text[:first_stage] + table + text[first_stage:]
report.write_text(text)
PY

rm -f "$TABLE" "$TMP"

# The audit intentionally exits success even when build stages fail. Individual
# exit codes are the evidence Phase 2 is collecting; CI failure would hide later
# stages and make the report less useful.
exit 0
