#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CPSYCLE="$ROOT/cpsycle"
OUT="${1:-$ROOT/build-audit}"
mkdir -p "$OUT/logs"

REPORT="$OUT/summary.md"
HEADER="$OUT/header.md"
DETAILS="$OUT/details.md"
: > "$HEADER"
: > "$DETAILS"

declare -a status_rows=()
declare -a build_stage_ids=()
declare -A stage_results=()
declare -A stage_exit_codes=()

record_stage() {
    local id="$1"
    local label="$2"
    local result="$3"
    local rc="$4"
    local log="$5"

    stage_results["$id"]="$result"
    stage_exit_codes["$id"]="$rc"
    status_rows+=("| ${label} | ${result} | ${rc} | logs/${log} |")

    case "$id" in
        clean-*) ;;
        *) build_stage_ids+=("$id") ;;
    esac
}

run_stage_with_prereqs() {
    local id="$1"
    local label="$2"
    local prereqs="$3"
    shift 3
    local log_name="${id}.log"
    local log="$OUT/logs/$log_name"
    local prerequisite_blocked=0

    if [ -n "$prereqs" ]; then
        local prerequisite
        IFS=',' read -r -a prerequisite_list <<< "$prereqs"
        for prerequisite in "${prerequisite_list[@]}"; do
            if [ "${stage_results[$prerequisite]:-NOT_RUN}" != "PASS" ]; then
                prerequisite_blocked=1
                break
            fi
        done
    fi

    printf '## %s\n\n' "$label" >> "$DETAILS"
    printf 'Command: `%s`\n\n' "$*" >> "$DETAILS"
    if [ -n "$prereqs" ]; then
        printf 'Prerequisites: `%s`\n\n' "$prereqs" >> "$DETAILS"
    fi

    set +e
    (cd "$CPSYCLE" && "$@") >"$log" 2>&1
    local rc=$?
    set -e

    local result
    if [ "$rc" -eq 0 ]; then
        result="PASS"
    elif [ "$prerequisite_blocked" -eq 1 ]; then
        result="BLOCKED"
    else
        result="FAIL"
    fi

    record_stage "$id" "$label" "$result" "$rc" "$log_name"

    printf 'Result: `%s`\n\n' "$result" >> "$DETAILS"
    printf 'Exit code: `%s`\n\n' "$rc" >> "$DETAILS"
    printf 'Last 80 log lines:\n\n```text\n' >> "$DETAILS"
    tail -n 80 "$log" >> "$DETAILS" || true
    printf '\n```\n\n' >> "$DETAILS"
}

run_stage() {
    local id="$1"
    local label="$2"
    shift 2
    run_stage_with_prereqs "$id" "$label" "" "$@"
}

purge_untracked_native_artifacts() {
    local artifact rel
    local tracked_match=0

    while IFS= read -r -d '' artifact; do
        rel="${artifact#$ROOT/}"
        if git -C "$ROOT" ls-files --error-unmatch -- "$rel" >/dev/null 2>&1; then
            printf 'Refusing to remove Git-tracked native artifact: %s\n' "$rel" >&2
            tracked_match=1
            continue
        fi
        rm -f -- "$artifact"
        printf 'Removed stale native artifact: %s\n' "$rel"
    done < <(
        find "$CPSYCLE" -type f \
            \( -name '*.o' -o -name '*.a' -o -name '*.so' -o -name '*.lo' -o -name '*.gch' \
               -o -name 'psycle' -o -name 'psyplayer' \) \
            -print0
    )

    # The historical driver clean removes files inside this generated directory
    # but leaves the directory itself behind. Preserve a tracked directory tree
    # if one is ever introduced; otherwise remove it to reproduce a fresh clone.
    if git -C "$ROOT" ls-files -- 'cpsycle/driver/build/*' | grep -q .; then
        printf 'Refusing to remove cpsycle/driver/build because it contains Git-tracked files.\n' >&2
        tracked_match=1
    else
        rm -rf "$CPSYCLE/driver/build"
        printf 'Removed generated directory: cpsycle/driver/build\n'
    fi

    return "$tracked_match"
}

run_artifact_purge_stage() {
    local id='clean-artifacts'
    local label='Generated artifact purge'
    local log_name="${id}.log"
    local log="$OUT/logs/$log_name"

    printf '## %s\n\n' "$label" >> "$DETAILS"
    printf 'Command: `%s`\n\n' 'purge untracked native build artifacts' >> "$DETAILS"

    set +e
    purge_untracked_native_artifacts >"$log" 2>&1
    local rc=$?
    set -e

    local result='PASS'
    if [ "$rc" -ne 0 ]; then
        result='FAIL'
    fi
    record_stage "$id" "$label" "$result" "$rc" "$log_name"

    printf 'Result: `%s`\n\n' "$result" >> "$DETAILS"
    printf 'Exit code: `%s`\n\n' "$rc" >> "$DETAILS"
    printf 'Last 80 log lines:\n\n```text\n' >> "$DETAILS"
    tail -n 80 "$log" >> "$DETAILS" || true
    printf '\n```\n\n' >> "$DETAILS"
}

record_environment() {
    {
        echo '# PSYCLE-LINUX Phase 2 Build Audit'
        echo
        echo 'Generated by `scripts/phase2-build-audit.sh`.'
        echo
        echo '## Environment'
        echo
        echo '```text'
        uname -a
        echo
        if command -v lsb_release >/dev/null 2>&1; then lsb_release -a 2>/dev/null || true; fi
        echo
        gcc --version | head -n 1 || true
        g++ --version | head -n 1 || true
        make --version | head -n 1 || true
        pkg-config --version || true
        echo '```'
        echo
        echo '## pkg-config integration points'
        echo
        echo '| module | version | cflags | libs |'
        echo '| --- | --- | --- | --- |'
    } >> "$HEADER"

    local module version cflags libs
    for module in lua lua5.4 lilv-0 freetype2 fontconfig x11 xft xext xmu alsa jack sdl2 fluidsynth; do
        version="$(pkg-config --modversion "$module" 2>/dev/null || true)"
        cflags="$(pkg-config --cflags "$module" 2>/dev/null || true)"
        libs="$(pkg-config --libs "$module" 2>/dev/null || true)"
        [ -n "$version" ] || version='MISSING'
        printf '| `%s` | `%s` | `%s` | `%s` |\n' "$module" "$version" "$cflags" "$libs" >> "$HEADER"
    done
    echo >> "$HEADER"
}

finalize_report() {
    {
        cat "$HEADER"
        echo '## Stage status'
        echo
        echo '| stage | result | exit | log |'
        echo '| --- | --- | ---: | --- |'
        printf '%s\n' "${status_rows[@]}"
        echo
        cat "$DETAILS"
    } > "$REPORT"
}

record_environment

# A repeatable audit must not reuse stale outputs. Run the historical clean
# targets first, then purge generated native artifacts those makefiles miss
# (including nested plugin objects and flattened X11 UI objects).
run_stage clean-top-level 'Top-level clean' make clean
run_stage clean-drivers 'Driver clean' make clean-drivers
run_artifact_purge_stage

# If any cleanup stage fails, stop before a build stage can mistake stale output
# for current evidence. The workflow uploads the partial report with if: always().
if [ "${stage_results[clean-top-level]}" != "PASS" ] || \
   [ "${stage_results[clean-drivers]}" != "PASS" ] || \
   [ "${stage_results[clean-artifacts]}" != "PASS" ]; then
    finalize_report
    echo 'Cleanup failed; refusing to audit potentially stale build artifacts.' >&2
    exit 2
fi

# Build libraries in dependency order so each layer has an independent result.
run_stage core-container 'Core: container' make -C container/src
run_stage core-thread 'Core: thread' make -C thread/src
run_stage core-script 'Core: script' make -C script/src
run_stage core-file 'Core: file' make -C file/src
run_stage core-dsp 'Core: DSP' make -C dsp/src
run_stage ui-x11 'UI: X11/Xft' make -C ui/src
run_stage core-luaui 'Core: Lua UI' make -C luaui/src
run_stage core-audio 'Core: audio engine' make -C audio/src

# Linux drivers are still executed independently. If they return nonzero while
# core prerequisites are unavailable, report BLOCKED rather than mislabelling
# the downstream failure as a driver-specific FAIL.
run_stage_with_prereqs driver-alsa 'Driver: ALSA' 'core-container,core-dsp' make -C driver/alsa
run_stage_with_prereqs driver-alsamidi 'Driver: ALSA MIDI' 'core-container,core-dsp' make -C driver/alsamidi
run_stage_with_prereqs driver-jack 'Driver: JACK' 'core-container,core-dsp' make -C driver/jack
run_stage_with_prereqs driver-sdl2 'Driver: SDL2' 'core-container,core-dsp' make -C driver/sdl2
run_stage_with_prereqs driver-evjoystick 'Driver: event joystick' 'core-container,core-dsp' make -C driver/evjoystick

# Aggregate targets are still executed for evidence, but their prerequisite
# lists mirror the imported makefiles so a failed library is reported as the
# causal blocker rather than creating a misleading independent FAIL.
run_stage_with_prereqs player 'psyplayer' 'core-script,core-thread,core-container,core-file,core-dsp,core-audio' make player
run_stage_with_prereqs host 'Native X11 host' 'core-script,core-thread,core-container,core-file,ui-x11,core-luaui,core-dsp,core-audio' make host
run_stage_with_prereqs plugins 'Native plugin set' 'core-container,core-dsp' make plugins
run_stage_with_prereqs drivers-aggregate 'Aggregate Linux drivers' 'core-container,core-dsp' make drivers
run_stage_with_prereqs full-build 'Top-level make all' 'core-script,core-thread,core-container,core-file,ui-x11,core-luaui,core-dsp,core-audio' make all

finalize_report

# The harness deliberately runs every stage before deciding success. Unlike the
# original audit script, it does not unconditionally return zero: any FAIL or
# BLOCKED build stage makes the command fail after the complete report exists.
audit_rc=0
for id in "${build_stage_ids[@]}"; do
    if [ "${stage_results[$id]}" != "PASS" ]; then
        audit_rc=1
        break
    fi
done

if [ "$audit_rc" -ne 0 ]; then
    echo 'Build audit completed with failing or blocked stages; see summary.md.' >&2
fi

exit "$audit_rc"
