#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/phase6c-evidence}"
[[ "$OUT" = /* ]] || OUT="$ROOT/$OUT"
PLAYER="${PSYCLE_PHASE6C_PLAYER:-$ROOT/psycle-cpp-r12005-sanitized/psycle-player/++qmake/psycle-player}"

if [[ -e "$OUT" ]] && [[ -n "$(find "$OUT" -mindepth 1 -print -quit 2>/dev/null)" ]]; then
    echo "phase6c-candidate-fixtures: refusing non-empty output directory: $OUT" >&2
    exit 2
fi
mkdir -p "$OUT"

[[ -x "$PLAYER" ]] || {
    echo "phase6c-candidate-fixtures: missing historical player: $PLAYER" >&2
    exit 2
}

python3 "$ROOT/scripts/phase6c-validate-matrix.py" \
    "$ROOT/phase6c/compatibility-matrix.json" | tee "$OUT/matrix-validation.log"

# Generate project-authored fixtures through the existing C-Psycle regression
# corpus. These establish a reproducible shared input; they are not treated as
# original-Psycle behavioural truth.
bash "$ROOT/scripts/phase4-historical-psy2-smoke.sh" "$OUT/cpsycle-psy2" \
    >"$OUT/cpsycle-psy2.log" 2>&1
bash "$ROOT/scripts/phase4-core-workflow-smoke.sh" "$OUT/cpsycle-psy3" \
    >"$OUT/cpsycle-psy3.log" 2>&1

PSY2="$OUT/cpsycle-psy2/phase4-historical-psy2.psy"
PSY3="$OUT/cpsycle-psy3/phase4-first.psy"
[[ -s "$PSY2" ]] || { echo "missing generated PSY2 fixture" >&2; exit 2; }
[[ -s "$PSY3" ]] || { echo "missing generated PSY3 fixture" >&2; exit 2; }
[[ "$(dd if="$PSY2" bs=1 count=8 status=none)" == "PSY2SONG" ]] || {
    echo "unexpected PSY2 fixture signature" >&2
    exit 2
}
[[ "$(dd if="$PSY3" bs=1 count=4 status=none)" == "PSY3" ]] || {
    echo "unexpected PSY3 fixture signature" >&2
    exit 2
}

collect_load() {
    local name="$1"
    local fixture="$2"
    local receipt="$OUT/candidate-${name}.json"
    local log="$OUT/candidate-${name}.log"
    local rc observation fixture_sha log_sha

    set +e
    timeout 20s "$PLAYER" --output-driver dummy --input-file "$fixture" \
        </dev/null >"$log" 2>&1
    rc=$?
    set -e

    if [[ "$rc" -eq 127 ]]; then
        echo "phase6c-candidate-fixtures: player command could not execute" >&2
        return 2
    fi
    if [[ "$rc" -eq 0 ]]; then
        observation="load-and-clean-exit"
    elif [[ "$rc" -eq 124 ]]; then
        observation="timeout"
    elif [[ "$rc" -gt 128 ]]; then
        observation="terminated-by-signal-$((rc - 128))"
    else
        observation="load-returned-nonzero"
    fi

    fixture_sha="$(sha256sum "$fixture" | awk '{print $1}')"
    log_sha="$(sha256sum "$log" | awk '{print $1}')"

    python3 - "$receipt" "$name" "$fixture" "$fixture_sha" "$log" "$log_sha" "$rc" "$observation" <<'PY'
import json
import pathlib
import sys

receipt, name, fixture, fixture_sha, log, log_sha, rc, observation = sys.argv[1:]
payload = {
    "schema_version": 1,
    "phase": "6C",
    "scope": "candidate-only-load-observation",
    "contract": f"project-io-{name}-parse",
    "candidate": {
        "source_revision": "SourceForge SVN r12005",
        "phase6b_baseline_sha256": "00cd95562b78303b82e17f62fff4b58622f7c0e78c0b4dd850d448082a53893a",
        "executable": "psycle-cpp-r12005-sanitized/psycle-player/++qmake/psycle-player",
        "command": "psycle-player --output-driver dummy --input-file <fixture>",
        "exit_code": int(rc),
        "observation": observation,
    },
    "fixture": {
        "path": pathlib.Path(fixture).name,
        "sha256": fixture_sha,
        "origin": "project-authored C-Psycle regression fixture",
    },
    "log": {"path": pathlib.Path(log).name, "sha256": log_sha},
    "original_psycle_observed": False,
    "parity_status": "UNKNOWN",
    "parity_note": "Candidate execution evidence alone cannot classify compatibility with the pinned original Psycle reference."
}
pathlib.Path(receipt).write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
PY

    printf 'phase6c-candidate-fixtures: %s rc=%s observation=%s fixture=%s\n' \
        "$name" "$rc" "$observation" "$fixture_sha"
}

collect_load psy2 "$PSY2"
collect_load psy3 "$PSY3"

cat >"$OUT/summary.md" <<'EOF'
# Phase 6C Candidate Fixture Evidence

This receipt set is intentionally **candidate-only**. It proves that the pinned
historical Linux `psycle-player` was exercised against shared project-authored
PSY2/PSY3 fixtures and records the exact result. It does not classify any row as
PASS / DIFFERENT / MISSING against original Psycle 1.12.0.

- Matrix schema/invariants: validated.
- PSY2 fixture: generated by the existing Phase 4 historical PSY2 regression.
- PSY3 fixture: generated by the existing Phase 4 core workflow regression.
- Candidate execution: recorded with dummy audio, exit code, fixture SHA-256 and log SHA-256.
- Original-Psycle observation: not performed by this workflow.
- Overall parity classification: remains UNKNOWN until versioned original-reference evidence exists.
EOF

cat "$OUT/candidate-psy2.json"
cat "$OUT/candidate-psy3.json"
cat "$OUT/summary.md"
